# This file was generated by GoReleaser. DO NOT EDIT.
cask "envault" do
  version "1.26.1"

  on_macos do
    on_intel do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Darwin_x86_64.zip",
        verified: "github.com/DinanathDash/Envault"
      sha256 "605336a6044961024b6e5277f9f3393b322a7d0e60c93acc459fe9916ba3b5b9"
    end
    on_arm do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Darwin_arm64.zip",
        verified: "github.com/DinanathDash/Envault"
      sha256 "bb738d8dab1918583118ab75cc9bc82669c94c11e683b037ad3a3b0ef6740c6f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Linux_x86_64.zip",
        verified: "github.com/DinanathDash/Envault"
      sha256 "15f56e7c410bca4429eda529cdd9ec2a75163711c9ef43314e2ddab14913b195"
    end
    on_arm do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Linux_arm64.zip",
        verified: "github.com/DinanathDash/Envault"
      sha256 "d0fdf56b5f26920dc815bc59bf99328a270d24e05a7b6fbf7264f7a17ba8ba97"
    end
  end

  name "envault"
  desc "Envault CLI - Securely manage your environment variables"
  homepage "https://envault.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envault"

  # No zap stanza required

end
