# This file was generated by GoReleaser. DO NOT EDIT.
cask "envault" do
  name "envault"
  desc "Envault CLI - Securely manage your environment variables"
  homepage "https://envault.tech"
  version "1.23.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envault"

  on_macos do
    on_intel do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Darwin_x86_64.tar.gz",
        verified: "github.com/DinanathDash/Envault"
      sha256 "b0e960a5da482217c24a98333c25ffa060f2e1b07d0c702be93dfd8fa36f02a2"
    end
    on_arm do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Darwin_arm64.tar.gz",
        verified: "github.com/DinanathDash/Envault"
      sha256 "8c2e85a6119161259d138bea17446f1c9e8b1704c8792ebfdf562e9ece345e54"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Linux_x86_64.tar.gz",
        verified: "github.com/DinanathDash/Envault"
      sha256 "ae7a0999ffa522e06d1826c8941bd2fe0198130ae3f1590860e0079ed06398b3"
    end
    on_arm do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Linux_arm64.tar.gz",
        verified: "github.com/DinanathDash/Envault"
      sha256 "327236fc2584a4f8456acf3bd27feedaa63fc5010ef383f695cd32abc3c78978"
    end
  end

  # No zap stanza required
end
