# This file was generated by GoReleaser. DO NOT EDIT.
cask "envault" do
  name "envault"
  desc "Envault CLI - Securely manage your environment variables"
  homepage "https://envault.tech"
  version "1.25.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envault"

  on_macos do
    on_intel do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Darwin_x86_64.tar.gz",
        verified: "github.com/DinanathDash/Envault"
      sha256 "056fe5d45e05f2cabc4ce10bc9ed8a73e76496bb67adfb25230cf926e0d71185"
    end
    on_arm do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Darwin_arm64.tar.gz",
        verified: "github.com/DinanathDash/Envault"
      sha256 "26b19f77b57c6c7c55ed4524ee6508cc38c1c04dce4d2351fcdfb8ffeb1b3e8d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Linux_x86_64.tar.gz",
        verified: "github.com/DinanathDash/Envault"
      sha256 "01214623e93e6663e3639b5ef871ca527684e493bb8567eb100e6edf2780c847"
    end
    on_arm do
      url "https://github.com/DinanathDash/Envault/releases/download/v#{version}/envault_Linux_arm64.tar.gz",
        verified: "github.com/DinanathDash/Envault"
      sha256 "1efeebdd6388b2ce563264ac121ca736ee5ba45deebcd97c147873a3540666d6"
    end
  end

  # No zap stanza required
end
