# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envault < Formula
  desc "Envault CLI - Securely manage your environment variables"
  homepage "https://envault.tech"
  version "1.36.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DinanathDash/Envault/releases/download/v1.36.0/envault_Darwin_x86_64.tar.gz"
      sha256 "364911d091d95856134da0adbd6b2268634649b4bfeff63c9bfeb08699e37bfe"

      define_method(:install) do
        bin.install "envault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DinanathDash/Envault/releases/download/v1.36.0/envault_Darwin_arm64.tar.gz"
      sha256 "a1b3c91d858008973803bbfea418742f6af1e0bbbe20ab01a3e0b915ac080ed4"

      define_method(:install) do
        bin.install "envault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DinanathDash/Envault/releases/download/v1.36.0/envault_Linux_x86_64.tar.gz"
      sha256 "f39caeb762f291a20b30e828821bce2c7f9c100231abebc389fc5364b1bf4691"
      define_method(:install) do
        bin.install "envault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DinanathDash/Envault/releases/download/v1.36.0/envault_Linux_arm64.tar.gz"
      sha256 "f79401cb8123a888ad53b8ead6633bc13b8659e6216f0a4ef82f726dc343df6a"
      define_method(:install) do
        bin.install "envault"
      end
    end
  end

  test do
    system "#{bin}/envault", "--version"
  end
end
